# Generated by Django 5.1.14 on 2025-11-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_user_custom_hotkeys"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("owner", "Owner"), ("contributor", "Contributor")],
                default="owner",
                help_text="User role type",
                max_length=20,
                verbose_name="role",
            ),
        ),
    ]
